const crud =
    [{
      path: '/act-idc-web/xxx/crudSample/pagingList.do',
      data: {
        'success': {
          'pageIndex': 0,
          'pageSize': 15,
          'rows': [
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 1,
              'sqlSentence': '语句1',
              'remark': '备注1',
              'plan': '计划1',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 2,
              'sqlSentence': '语句2',
              'remark': '备注2',
              'plan': '计划2',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 3,
              'sqlSentence': '语句3',
              'remark': '备注3',
              'plan': '计划3',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 4,
              'sqlSentence': '语句4',
              'remark': '备注4',
              'plan': '计划4',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 5,
              'sqlSentence': '语句5',
              'remark': '备注5',
              'plan': '计划5',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 6,
              'sqlSentence': '语句6',
              'remark': '备注6',
              'plan': '计划6',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 7,
              'sqlSentence': '语句7',
              'remark': '备注7',
              'plan': '计划7',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 8,
              'sqlSentence': '语句8',
              'remark': '备注8',
              'plan': '计划8',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 9,
              'sqlSentence': '语句9',
              'remark': '备注8',
              'plan': '计划9',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 10,
              'sqlSentence': '语句10',
              'remark': '备注10',
              'plan': '计划10',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 11,
              'sqlSentence': '语句11',
              'remark': '备注11',
              'plan': '计划11',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 12,
              'sqlSentence': '语句12',
              'remark': '备注12',
              'plan': '计划12',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 13,
              'sqlSentence': '语句13',
              'remark': '备注13',
              'plan': '计划13',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 14,
              'sqlSentence': '语句14',
              'remark': '备注14',
              'plan': '计划14',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            },
            {
              'exportType': null,
              'fileName': null,
              'uploadInfo': null,
              'engineId': 15,
              'sqlSentence': '语句15',
              'remark': '备注15',
              'plan': '计划15',
              'createDate': 1511322786000,
              'updateDate': 1511322784000,
              'creator': '系统管理员',
              'modifier': '系统管理员',
              'sqlSentenceQuery': null,
              'remarkQuery': null,
              'createDateQuery': null,
              'updateDateQuery': null,
              'creatorQuery': null,
              'modifierQuery': null
            }
          ],
          'total': 16,
          'totalPageCount': 2
        }
      }
    }
    ]

export default crud
